/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class project_application_core_NativeFunctions */

#ifndef _Included_project_application_core_NativeFunctions
#define _Included_project_application_core_NativeFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     project_application_core_NativeFunctions
 * Method:    bitPermutation
 * Signature: ([BI[JIZZI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_project_application_core_NativeFunctions_bitPermutation
  (JNIEnv *, jclass, jbyteArray, jint, jlongArray, jint, jboolean, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
