/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class project_algorythm_des_DESRoundFunction */

#ifndef _Included_project_algorythm_des_DESRoundFunction
#define _Included_project_algorythm_des_DESRoundFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     project_algorythm_des_DESRoundFunction
 * Method:    applyDesRoundFunction
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_project_algorythm_des_DESRoundFunction_applyDesRoundFunction
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     project_algorythm_des_DESRoundFunction
 * Method:    getFunctionAddressInLibrary
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_project_algorythm_des_DESRoundFunction_getFunctionAddressInLibrary
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
