/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class project_application_core_FeistelNetwork */

#ifndef _Included_project_application_core_FeistelNetwork
#define _Included_project_application_core_FeistelNetwork
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     project_application_core_FeistelNetwork
 * Method:    applyFeistelNetwork
 * Signature: ([B[[BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_project_application_core_FeistelNetwork_applyFeistelNetwork
  (JNIEnv *, jclass, jbyteArray, jobjectArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
